translations['zh-CN']=
{
    "factorio-quantizative-tool": "异星工厂量化计算工具",
    "name": "名字",
    "requirement-per-minute": "每分钟所需产量",
    "made-in": "制造于",
    "machine-number": "设备数量",
    "electric-consumption": "电力消耗",
    "pollution": "污染",
    "statistics": "统计",
    "select-language": "选择语言：",
    "alter-data": "修改数据",
    "show-demo": "显示范例",
    "cancel": "取消",
    "submit": "提交",
    "rebuild-icon": "重建图标",
    "remainder": "余量",
    "advanced-circuit": "集成电路",
    "atomic-bomb": "原子弹",
    "battery": "电池",
    "belt-immunity-equipment": "锚定模块",
    "blueprint": "蓝图 (建设规划)",
    "blueprint-book": "蓝图簿",
    "cannon-shell": "制式炮弹",
    "cluster-grenade": "集束手雷",
    "coal": "煤矿",
    "coin": "金币",
    "combat-shotgun": "冲锋霰弹枪",
    "computer": "计算机",
    "concrete": "混凝土",
    "copper-cable": "铜线",
    "copper-ore": "铜矿",
    "copper-plate": "铜板",
    "crude-oil-barrel": "原油桶",
    "deconstruction-planner": "红图 (拆除规划)",
    "defender-capsule": "防御机器人胶囊",
    "destroyer-capsule": "进攻机器人胶囊",
    "discharge-defense-remote": "放电防御发射器",
    "distractor-capsule": "掩护机器人胶囊",
    "effectivity-module": {
        "item-name": "节能插件 1",
        "technology-name": "节能插件"
    },
    "effectivity-module-2": "节能插件 2",
    "effectivity-module-3": "节能插件 3",
    "electric-energy-interface": "电力接口",
    "electric-engine-unit": "电动机",
    "electronic-circuit": "电路板",
    "empty-barrel": "空桶",
    "engine-unit": "内燃机",
    "explosive-cannon-shell": "爆破炮弹",
    "explosive-rocket": "爆破火箭弹",
    "explosive-uranium-cannon-shell": "爆破贫铀炮弹",
    "explosives": "炸药",
    "filled-barrel": "__1__桶",
    "firearm-magazine": "制式弹匣",
    "fish": "鱼",
    "flamethrower": {
        "item-name": "火焰喷射器",
        "technology-name": "火焰喷射"
    },
    "flamethrower-ammo": "油料储罐",
    "flamethrower-turret": "火焰炮塔",
    "flying-robot-frame": "机器人构架",
    "green-wire": "绿线缆",
    "grenade": "制式手雷",
    "hazard-concrete": "标识混凝土",
    "heavy-armor": {
        "item-name": "重型护甲",
        "technology-name": "重甲"
    },
    "high-tech-science-pack": "尖端科技包",
    "iron-axe": "铁斧镐",
    "iron-gear-wheel": "铁齿轮",
    "iron-ore": "铁矿",
    "iron-plate": "铁板",
    "iron-stick": "铁棒",
    "item-with-tags": "带标签的物品",
    "lab": "研究中心",
    "landfill": "填海材料",
    "laser-turret": "激光炮塔",
    "light-armor": "轻型护甲",
    "low-density-structure": "轻质框架",
    "military-science-pack": "军备科技包",
    "modular-armor": "模块装甲",
    "piercing-rounds-magazine": "穿甲弹匣",
    "piercing-shotgun-shell": "穿甲霰弹",
    "pistol": "手枪",
    "plastic-bar": "塑料",
    "poison-capsule": "剧毒胶囊",
    "power-armor": "能量装甲",
    "power-armor-mk2": "能量装甲MK2",
    "processing-unit": "处理器",
    "production-science-pack": "生产科技包",
    "productivity-module": {
        "item-name": "产能插件 1",
        "technology-name": "产能插件"
    },
    "productivity-module-2": "产能插件 2",
    "productivity-module-3": "产能插件 3",
    "rail": "铁轨",
    "rail-planner": "铁轨布局器",
    "railgun": "电磁枪",
    "railgun-dart": "电磁弹",
    "raw-fish": "鲜鱼",
    "raw-wood": "原木",
    "red-wire": "红线缆",
    "repair-pack": "修理包",
    "rocket": "火箭弹",
    "rocket-control-unit": "火箭控制器",
    "rocket-fuel": "火箭燃料",
    "rocket-launcher": "火箭筒",
    "rocket-part": "火箭组件",
    "satellite": "卫星",
    "science-pack-1": "科技包1",
    "science-pack-2": "科技包2",
    "science-pack-3": "科技包3",
    "shotgun": "霰弹枪",
    "shotgun-shell": "制式霰弹",
    "simple-entity-with-force": {
        "item-name": "阵营的简单实体",
        "entity-name": "阵营的简单设施"
    },
    "simple-entity-with-owner": {
        "item-name": "个人的简单实体",
        "entity-name": "个人的简单设施"
    },
    "slowdown-capsule": "减速胶囊",
    "small-plane": "小型飞机",
    "solar-panel": "太阳能板",
    "solid-fuel": "固体燃料",
    "space-science-pack": "太空科技包",
    "speed-module": {
        "item-name": "速度插件 1",
        "technology-name": "速度插件"
    },
    "speed-module-2": "速度插件 2",
    "speed-module-3": "速度插件 3",
    "steel-axe": "钢斧镐",
    "steel-plate": "钢材",
    "stone": "石头",
    "stone-brick": "石砖",
    "stone-path": "石基路",
    "submachine-gun": "冲锋枪",
    "sulfur": "硫磺",
    "tank-cannon": "坦克炮",
    "tank-flamethrower": "车载喷火器",
    "tank-machine-gun": "车载机枪",
    "uranium-235": "铀-235",
    "uranium-238": "铀-238",
    "uranium-cannon-shell": "贫铀炮弹",
    "uranium-fuel-cell": "铀燃料棒",
    "uranium-ore": "铀矿",
    "uranium-rounds-magazine": "贫铀弹匣",
    "used-up-uranium-fuel-cell": "乏燃料棒",
    "vehicle-machine-gun": "车载机枪",
    "wood": "木板",
    "accumulator": "蓄电器",
    "arithmetic-combinator": "算术运算器",
    "assembling-machine-1": "组装机1型",
    "assembling-machine-2": "组装机2型",
    "assembling-machine-3": "组装机3型",
    "beacon": "插件效果分享塔",
    "behemoth-biter": "巨型食人虫",
    "behemoth-biter-corpse": "巨型食人虫尸体",
    "behemoth-spitter": "巨型喷吐虫",
    "behemoth-spitter-corpse": "巨型喷吐虫尸体",
    "big-biter": "大型食人虫",
    "big-biter-corpse": "大型食人虫尸体",
    "big-electric-pole": "远程输电塔",
    "big-remnants": "废墟 (大)",
    "big-ship-wreck-1": "飞船残骸 (大)",
    "big-ship-wreck-2": "飞船残骸 (大)",
    "big-ship-wreck-3": "飞船残骸 (大)",
    "big-spitter": "大型喷吐虫",
    "big-spitter-corpse": "大型喷吐虫尸体",
    "big-worm-corpse": "大型沙虫尸体",
    "big-worm-turret": "大型沙虫",
    "biter-spawner": "食人虫巢",
    "biter-spawner-corpse": "食人虫巢残骸",
    "boiler": "锅炉",
    "burner-inserter": "热能机械臂",
    "burner-mining-drill": "热能采矿机",
    "car": "汽车",
    "cargo-wagon": "货运车厢",
    "centrifuge": "离心机",
    "character-corpse": "玩家尸体",
    "chemical-plant": "化工厂",
    "constant-combinator": "常量运算器",
    "construction-robot": "建设机器人",
    "crude-oil": "原油",
    "curved-rail": "曲线铁轨",
    "curved-rail-remnants": "曲线铁轨残骸",
    "dead-dry-hairy-tree": "枯枝树 (死)",
    "dead-grey-trunk": "灰树干 (死)",
    "dead-tree": "树 (死)",
    "decider-combinator": "判断运算器",
    "deconstructible-tile-proxy": "替代地貌",
    "defender": "防御机器人",
    "destroyer": "进攻机器人",
    "distractor": "掩护机器人",
    "dry-hairy-tree": "枯枝树",
    "dry-tree": "树 (枯)",
    "electric-furnace": "电炉",
    "electric-mining-drill": "电力采矿机",
    "entity-ghost": "建设预览",
    "express-loader": "极速装卸机",
    "express-splitter": "极速分流器",
    "express-transport-belt": "极速传送带",
    "express-underground-belt": "极速地下传送带",
    "fast-inserter": "高速机械臂",
    "fast-loader": "高速装卸机",
    "fast-splitter": "高速分流器",
    "fast-transport-belt": "高速传送带",
    "fast-underground-belt": "高速地下传送带",
    "filter-inserter": "筛选机械臂",
    "fluid-wagon": "液罐车厢",
    "gate": "闸门",
    "green-coral": "绿珊瑚",
    "gun-turret": "机枪炮塔",
    "heat-exchanger": "换热器",
    "heat-pipe": "热管",
    "inserter": "电力机械臂",
    "iron-chest": "铁制箱",
    "item-on-ground": "落地物品",
    "item-request-proxy": "物品需求",
    "land-mine": "地雷",
    "loader": "基础装卸机",
    "locomotive": "内燃机车",
    "logistic-chest-active-provider": "中转供货箱 (紫箱)",
    "logistic-chest-passive-provider": "按需供货箱 (红箱)",
    "logistic-chest-requester": "按需集货箱 (蓝箱)",
    "logistic-chest-storage": "中转集货箱 (黄箱)",
    "logistic-robot": "物流机器人",
    "long-handed-inserter": "加长机械臂",
    "market": "市场",
    "medium-biter": "中型食人虫",
    "medium-biter-corpse": "中型食人虫尸体",
    "medium-electric-pole": "中型电线杆",
    "medium-remnants": "废墟 (中)",
    "medium-ship-wreck": "飞船残骸 (中)",
    "medium-spitter": "中型喷吐虫",
    "medium-spitter-corpse": "中型喷吐虫尸体",
    "medium-worm-corpse": "中型沙虫尸体",
    "medium-worm-turret": "中型沙虫",
    "nuclear-reactor": "核反应堆",
    "offshore-pump": "供水泵",
    "oil-refinery": "炼油厂",
    "pipe": "管道",
    "pipe-to-ground": "地下管道",
    "player": "玩家",
    "player-port": "玩家出生点",
    "poison-cloud": "毒雾",
    "power-switch": "电闸",
    "programmable-speaker": "程控扬声器",
    "pump": "管道泵",
    "pumpjack": "抽油机",
    "radar": "雷达",
    "rail-chain-signal": "铁路联锁信号灯",
    "rail-signal": "铁路信号灯",
    "red-desert-rock-big": "岩石 (大)",
    "red-desert-rock-huge": "岩石 (巨)",
    "roboport": "机器人指令平台",
    "rocket-silo": "火箭发射井",
    "rocket-turret": "火箭炮塔",
    "small-biter": "小型食人虫",
    "small-biter-corpse": "小型食人虫尸体",
    "small-electric-pole": "小型电线杆",
    "small-lamp": "灯",
    "small-remnants": "废墟 (小)",
    "small-scorchmark": "焦痕 (小)",
    "small-ship-wreck": "飞船残骸 (小)",
    "small-spitter": "小型喷吐虫",
    "small-spitter-corpse": "小型喷吐虫尸体",
    "small-worm-corpse": "小型沙虫尸体",
    "small-worm-turret": "小型沙虫",
    "space-module-wreck": "太空舱残骸",
    "spitter-spawner": "喷吐虫巢",
    "spitter-spawner-corpse": "喷吐虫巢残骸",
    "splitter": "基础分流器",
    "stack-filter-inserter": "集装筛选机械臂",
    "stack-inserter": "集装机械臂",
    "steam-engine": "蒸汽机",
    "steam-turbine": "汽轮机",
    "steel-chest": "钢制箱",
    "steel-furnace": "钢炉",
    "stone-furnace": "石炉",
    "stone-rock": "岩石",
    "stone-wall": "石墙",
    "storage-tank": "储液罐",
    "straight-rail": "直线铁轨",
    "straight-rail-remnants": "直线铁轨残骸",
    "substation": "广域配电站",
    "tank": "坦克",
    "tile-ghost": "地貌预览",
    "train-stop": "火车站",
    "transport-belt": "基础传送带",
    "tree-01": "树",
    "tree-01-stump": "树桩",
    "tree-02": "树",
    "tree-02-red": "树 (红)",
    "tree-02-stump": "树桩",
    "tree-03": "树",
    "tree-03-stump": "树桩",
    "tree-04": "树",
    "tree-04-stump": "树桩",
    "tree-05": "树",
    "tree-05-stump": "树桩",
    "tree-06": "树",
    "tree-06-brown": "树 (棕)",
    "tree-06-stump": "树桩",
    "tree-07": "树",
    "tree-07-stump": "树桩",
    "tree-08": "树",
    "tree-08-brown": "树 (棕)",
    "tree-08-red": "树 (红)",
    "tree-08-stump": "树桩",
    "tree-09": "树",
    "tree-09-brown": "树 (棕)",
    "tree-09-red": "树 (红)",
    "tree-09-stump": "树桩",
    "underground-belt": "基础地下传送带",
    "wall-remnants": "墙壁残骸",
    "water-well-pump": "水井泵",
    "wooden-chest": "木制箱",
    "heavy-oil": "重油",
    "light-oil": "轻油",
    "lubricant": "润滑油",
    "petroleum-gas": "石油气",
    "steam": "蒸汽",
    "sulfuric-acid": "硫酸",
    "water": "水",
    "battery-equipment": "电池组模块",
    "battery-mk2-equipment": "电池组模块MK2",
    "discharge-defense-equipment": "放电防御模块",
    "energy-shield-equipment": "能量盾模块",
    "energy-shield-mk2-equipment": "能量盾模块MK2",
    "exoskeleton-equipment": "外骨骼模块",
    "fusion-reactor-equipment": "聚变堆模块",
    "night-vision-equipment": "夜视模块",
    "personal-laser-defense-equipment": "激光防御模块",
    "personal-roboport-equipment": "机器人指令模块",
    "personal-roboport-mk2-equipment": "机器人指令模块MK2",
    "solar-panel-equipment": "太阳能模块",
    "advanced-oil-processing": "高等原油处理",
    "basic-oil-processing": "基础原油处理",
    "coal-liquefaction": "煤炭液化",
    "empty-crude-oil-barrel": "倒出原油",
    "empty-filled-barrel": "倒出 __1__",
    "fill-barrel": "灌装 __1__",
    "fill-crude-oil-barrel": "灌装原油",
    "heavy-oil-cracking": "重油裂解",
    "kovarex-enrichment-process": "Kovarex 铀增殖处理",
    "light-oil-cracking": "轻油裂解",
    "nuclear-fuel-reprocessing": "乏燃料后处理",
    "uranium-processing": "铀浓缩处理",
    "advanced-chemistry": "高等化学",
    "advanced-electronics": "高等电学",
    "advanced-material-processing": "高等冶炼技术",
    "alien-technology": "异星科技",
    "auto-character-logistic-trash-slots": "背包物流系统-回收清单",
    "automated-construction": "建设自动化",
    "automated-rail-transportation": "铁路自动运输系统",
    "automation": "自动化",
    "automobilism": "汽车",
    "braking-force": "制动技术",
    "bullet-damage": "子弹伤害",
    "bullet-speed": "子弹射速",
    "cannon-shell-damage": "炮弹伤害",
    "cannon-shell-speed": "炮弹射速",
    "character-logistic-slots": "背包物流系统-供应清单",
    "character-logistic-trash-slots": "背包物流系统-回收区",
    "chemistry": "基础化学",
    "circuit-network": "信号网络",
    "combat-robot-damage": "战斗机器人伤害",
    "combat-robotics": "战斗机器人",
    "construction-robotics": "建设机器人",
    "effect-transmission": "插件效果分享",
    "electric-energy-accumulators-1": "电能储存",
    "electric-energy-distribution": "电能传输",
    "electric-engine": "电动机",
    "electronics": "基础电学",
    "engine": "内燃机",
    "explosive-rocketry": "爆破火箭弹",
    "flamethrower-damage": "火焰伤害",
    "flammables": "燃烧技术",
    "fluid-handling": "流体操作",
    "flying": "悬空飞行技术",
    "follower-robot-count": "机器人跟随数量",
    "gates": "闸门",
    "grenade-damage": "手雷伤害",
    "gun-turret-damage": "机枪炮塔伤害",
    "inserter-capacity-bonus": "机械臂搬运量加成",
    "laser": "激光",
    "laser-turret-damage": "激光炮塔伤害",
    "laser-turret-speed": "激光炮塔射速",
    "laser-turrets": "激光炮塔",
    "logistic-robotics": "物流机器人",
    "logistic-system": "物流系统",
    "logistics": "物流学",
    "military": "军工学",
    "mining-productivity": "采矿产能",
    "modules": "插件",
    "nuclear-power": "核能",
    "oil-processing": "基础原油处理",
    "optics": "基础光学",
    "plastics": "塑料",
    "rail-signals": "铁路信号",
    "railway": "铁路",
    "research-speed": "研究中心研发速度",
    "robotics": "机器人技术",
    "rocket-damage": "火箭弹伤害",
    "rocket-speed": "火箭弹射速",
    "rocketry": "火箭弹",
    "shotgun-shell-damage": "霰弹伤害",
    "shotgun-shell-speed": "霰弹射速",
    "solar-energy": "太阳能",
    "steel-processing": "炼钢技术",
    "stone-walls": "石墙",
    "sulfur-processing": "硫磺",
    "tanks": "坦克",
    "toolbelt": "工具腰带",
    "turrets": "机枪炮塔",
    "uranium-ammo": "贫铀弹",
    "worker-robots-speed": "作业机器人移动速度",
    "worker-robots-storage": "作业机器人货物运量"
}
